const DASHBOARD_PATH = "/dashboard";
const CATEGORY_PATH = `${DASHBOARD_PATH}/category`;
const PRODUCT_PATH = `${DASHBOARD_PATH}/product`;
const PRODUCT_V2_PATH = `${DASHBOARD_PATH}/product-v2`;
const USER_PATH = `${DASHBOARD_PATH}/user`;
const BRANCH_PATH = `${DASHBOARD_PATH}/branch`;
const REPORT_PATH = `${DASHBOARD_PATH}/report`;
const FEEDBACK_PATH = `${DASHBOARD_PATH}/feedback`;

export const PATHS = {
    DASHBOARD: DASHBOARD_PATH,
    CATEGORY_DASHBOARD: CATEGORY_PATH,
    PRODUCT_DASHBOARD: PRODUCT_PATH,
    PRODUCT_V2_DASHBOARD: PRODUCT_V2_PATH,
    USER_DASHBOARD: USER_PATH,
    BRANCH_DASHBOARD: BRANCH_PATH,
    REPORT_DASHBOARD: REPORT_PATH,
    FEEDBACK_DASHBOARD: FEEDBACK_PATH,
};
